language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  include:
    - stage: lint
      name: "Rust: rustfmt"
      rust: stable
      install:
        - rustup component add rustfmt
      script:
        - cargo fmt -v -- --check
notifications:
  email: false
